name: CI

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    name: Run Tests and deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: LucasG04
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t LucasG04/prometheus-nodejs-app .
          docker tag LucasG04/prometheus-nodejs-app LucasG04/prometheus-nodejs-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push LucasG04/prometheus-nodejs-app